### ISSUE TITLE
TooManyRequestException in Library

### ISSUE THREAD

**Issue by sulemankhan447** [gojek/courier-android#44] opened 2022-09-26 08:12 UTC
Caused by android.net.ConnectivityManager$TooManyRequestsException
android.net.ConnectivityManager.convertServiceException (ConnectivityManager.java:3609)

android.net.ConnectivityManager.registerDefaultNetworkCallback (ConnectivityManager.java:4256)
com.gojek.networktracker.NetworkStateTrackerImpl.startTracking$network_tracker_release (NetworkStateTrackerImpl.java:115)
com.gojek.networktracker.NetworkStateTrackerImpl.addListener (NetworkStateTrackerImpl.java:86)
com.gojek.keepalive.OptimalKeepAliveCalculator.<init> (OptimalKeepAliveCalculator.java:31)
com.gojek.keepalive.KeepAliveCalculatorFactory.create (KeepAliveCalculatorFactory.java:29)
com.gojek.keepalive.OptimalKeepAliveProvider.<init> (OptimalKeepAliveProvider.java:16)
com.gojek.keepalive.OptimalKeepAliveProvider.<init> (OptimalKeepAliveProvider.java:9)
com.gojek.mqtt.client.internal.MqttClientInternal.initialiseOptimalKeepAliveProvider (MqttClientInternal.java:157)
com.gojek.mqtt.client.internal.MqttClientInternal.initialiseAdaptiveMqttClient (MqttClientInternal.java:122)
com.gojek.mqtt.client.internal.MqttClientInternal.<init> (MqttClientInternal.java:64)

**Comment by anubhav7nov** [comment] 2022-09-26 16:09
hey @sulemankhan447 can you add more details:  Steps to reproduce this issue? 
Since android 12, os imposed 100 callback limit. It may be due to some other lib or code path as well. Ref issue: https://issuetracker.google.com/issues/231499040

**Comment by sulemankhan447** [comment] 2022-09-26 17:25
Thanks @anubhav7nov for the reply, unfortunately we are not able to recreate this crash, as per our stack trace its was leading to courier library,
we will also look into work manager used in our code.

**Comment by anubhav7nov** [comment] 2022-10-03 04:48
@sulemankhan447 were you able to reproduce the issue or steps to reproduce this issue?

**Comment by anubhav7nov** [comment] 2022-10-04 09:52
Closing this issue as not reproducible.

**Closed by anubhav7nov** 2022-10-04 09:52 UTC
